### ISSUE TITLE
1.2 Patches for "Metal Gear Solid" uses SmithingSpeed

### ISSUE THREAD

**Issue by VilcsiTH** [emipa606/CamouflageandStealth#1]
\1.2\Patches\Patch_MSG.xml still uses SmithingSpeed as workSpeedStat. This throws a red error when attempting to load both mods.
Changing SmithingSpeed to GeneralLaborSpeed loads the game without throwing an error. (Haven't tested further compatibility between the two mods, it's possible that there are more issues between the two mods.)

"Metal Gear Solid" mod: https://steamcommunity.com/sharedfiles/filedetails/?id=1927048814

**Comment by emipa606** [comment]
Thanks, should be fixed now!
